Repository ubclaunchpad/rocket2, pull requests merged in 2019-03, with the labels that each got.

#216 Rwblickhan/#215 add rocket token command
  Pipfile
  Pipfile.lock
  command/commands/token.py
  command/core.py
  config.toml
  factory/__init__.py
  tests/command/commands/token_test.py
  tests/command/core_test.py
Labels: 👁Ready for Review

#228 Karma doc
  docs/Database.md
  docs/KarmaCommands.md
Labels: 👁Ready for Review

#213 #163 (Add Github TeamMember interface)
  interface/github.py
  tests/interface/github_test.py
Labels: 👁Ready for Review

#248 Jacqueschen1/team leads fields
  command/commands/team.py
  docs/Database.md
  docs/TeamCommands.md
  docs/UserCommands.md
  model/team.py
  tests/command/commands/team_test.py
  tests/model/team_test.py
Labels: 👁Ready for Review

#252 Adding karma field to user
  model/user.py
  tests/db/dynamodb_test.py
  tests/model/user_test.py
  tests/util.py
Labels: 👁Ready for Review

#251 Replaced time.time with UUID and passes tests
  model/project.py
  tests/model/project_test.py
Labels: 👁Ready for Review

#245 Webhook events send a message to designated bot channel
  command/core.py
  config.toml
  factory/__init__.py
  interface/slack.py
  server/server.py
  tests/interface/slack_test.py
Labels: 👀Ready for Re-Review

#259 refactor credentials loading
  .gitignore
  config.toml
  config/__init__.py
  config/credentials.py
  db/dynamodb.py
  factory/__init__.py
  server/server.py
  tests/config/__init__.py
  tests/config/test_credentials.py
  tests/credentials/complete/aws.toml
  tests/credentials/complete/github_signing_key.pem
  tests/credentials/complete/slack.toml
  tests/credentials/missing_fields/aws.toml
  tests/credentials/missing_fields/github_signing_key.pem
  tests/credentials/missing_fields/slack.toml
  tests/credentials/missing_files/invalid.toml
  tests/db/dynamodb_test.py
Labels: 👁Ready for Review

#258 Use formatted strings (f-strings)everywhere
  command/commands/user.py
  command/core.py
  db/dynamodb.py
  db/facade.py
  interface/slack.py
  server/server.py
  tests/command/commands/team_test.py
  tests/command/commands/user_test.py
  tests/webhook/webhook_test.py
Labels: 👁Ready for Review

#247 Michaelfu1029/#166 create membership GitHub webhooks
  tests/webhook/webhook_test.py
  webhook/webhook.py
Labels: 👀Ready for Re-Review

#263 Add type annotations and static type checking
  .gitignore
  Pipfile
  Pipfile.lock
  command/__init__.py
  command/commands/__init__.py
  command/commands/team.py
  command/commands/token.py
  command/commands/user.py
  command/core.py
  command/util.py
  conf.py
  db/dynamodb.py
  db/facade.py
  docs/api/model.rst
  factory/__init__.py
  index.rst
  interface/github.py
  interface/slack.py
  model/permissions.py
  model/project.py
  model/team.py
  model/user.py
  mypy.ini
  scripts/build_check.sh
  server/server.py
  tests/command/commands/user_test.py
  tests/util.py
  webhook/webhook.py
Labels: 👁Ready for Review

#264 Fix rtd docs build that is failing
  docs/doc_reqs.txt
Labels: 👁Ready for Review

#267 uninstalled seasurf
  Pipfile
  Pipfile.lock
  server/server.py
Labels: 👁Ready for Review

#275 Add bulk retrieving function and querying with union to DynamoDB
  db/dynamodb.py
  db/facade.py
  tests/db/dynamodb_test.py
  tests/db/facade_test.py
Labels: 👁Ready for Review

#268 Secure GitHub webhooks
  config/credentials.py
  factory/__init__.py
  server/server.py
  tests/config/credentials_test.py
  tests/credentials/complete/github.toml
  tests/credentials/missing_fields/github.toml
  tests/webhook/webhook_test.py
  webhook/webhook.py
Labels: 👀Ready for Re-Review

#280 Raven c/#273,279 config and credential fixes
  config/credentials.py
  docs/LocalDevelopmentGuide.md
  tests/config/credentials_test.py
Labels: 👁Ready for Review

#283 implement, test, and refactor slack code formatting
  command/commands/token.py
  command/core.py
  tests/command/core_test.py
  tests/utils/slack_msg_fmt_test.py
  utils/__init__.py
  utils/slack_msg_fmt.py
Labels: refactoring & cleanup, 👁Ready for Review

#269 Jacqueschen1/142 team commands
  command/commands/team.py
  command/commands/user.py
  command/core.py
  command/util.py
  interface/github.py
  model/team.py
  tests/command/commands/team_test.py
  tests/command/core_test.py
  tests/command/util_test.py
  tests/interface/github_test.py
  tests/model/team_test.py
  tests/webhook/webhook_test.py
  webhook/webhook.py
Labels: 👁Ready for Review
